"""
Experiment entry point.

This script contains the main logic for running an experiment and
persisting its outputs in a structured, reproducible format.

Generated by the experiment initializer.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Any


def run_experiment() -> Dict[str, Any]:
    """
    Execute the experiment logic.

    Returns:
        A dictionary containing experiment metrics and results.
    """
    # ------------------------------------------------------------------
    # TODO: Replace this section with your experiment logic
    # ------------------------------------------------------------------
    accuracy = 0.85

    return {
        "accuracy": accuracy,
    }


def write_outputs(outputs: Dict[str, Any], output_dir: Path) -> None:
    """
    Persist experiment outputs to disk.

    Args:
        outputs: Experiment results and metrics.
        output_dir: Directory where outputs will be written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    metrics_path = output_dir / "metrics.json"
    with metrics_path.open("w", encoding="utf-8") as f:
        json.dump(outputs, f, indent=2)

    print(f"✓ Metrics written to {metrics_path}")


def main() -> None:
    """
    Main execution entry point.
    """
    outputs_dir = Path("outputs")

    results = run_experiment()
    write_outputs(results, outputs_dir)


if __name__ == "__main__":
    main()
